### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Populate the database with some data
POST {{url}}/hotels/populate/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "jon",
    "password": "1234"
}

###
POST {{url}}/auth/login/

{
    "username": "jon",
    "password": "1234"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/hotels
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/hotels/23

###
POST {{url}}/hotels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJKb24gQmVydGVsc2VuIiwic3ViIjoiam9uIiwiZXhwIjoxNzMzMTM0NzUwLCJyb2xlcyI6ImFkbWluLHVzZXIiLCJ1c2VybmFtZSI6ImpvbiJ9.ztzysijeW8CLyjKUr3kPbBSwQ2uDWLyASkxHIj6GFag

{
  "hotelName": "Holiday Inn",
  "hotelAddress": "Stuttgart",
  "hotelType": "STANDARD"
}

###
PUT {{url}}/hotels/3
Content-Type: application/json

{
  "hotelName": "Ritz Carlton",
  "hotelAddress": "London City",
  "hotelType": "LUXURY"
}

###
DELETE {{url}}/hotels/2
Authorization: Bearer {{jwt_token}}

// Room API
###
GET {{url}}/rooms
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/rooms/1
Authorization: Bearer {{jwt_token}}

###
POST {{url}}/rooms/hotel/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "roomNumber": 11,
  "roomPrice": 1150,
  "roomType": "SINGLE"
}
